In [1]:
# Import all neccessary libraries
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [2]:
# Load data 
data = pd.read_csv('iris.csv')
data.head()

sepal_length  sepal_width  petal_length  petal_width species  Output
0           5.1          3.5           1.4          0.2  setosa       1
1           4.9          3.0           1.4          0.2  setosa       1
2           4.7          3.2           1.3          0.2  setosa       1
3           4.6          3.1           1.5          0.2  setosa       1
4           5.0          3.6           1.4          0.2  setosa       1

In [3]:
# Load Features
X = np.array(data[['sepal_length','sepal_width','petal_length', 'petal_width']]) 
# Load labels
y = np.array(data['Output'])
#X
#y

In [4]:
# Shuffling
indices = np.arange(len(X))
np.random.shuffle(indices)
X = X[indices]
y = y[indices]

In [5]:
# Train Test Split
split_ratio = 0.8
split_idx = int(split_ratio * len(X))
X_train, X_test = X[:split_idx], X[split_idx:]
y_train, y_test = y[:split_idx], y[split_idx:]
#X_train.shape, X_test.shape, y_train.shape, y_test.shape

In [16]:
# Algorithm [Test Prediction]
k = 5
model = KNeighborsClassifier(n_neighbors=k)
model.fit(X_train, y_train)
y_test_predicted = model.predict(X_test)
print(y_test_predicted)
print(y_test)

[0 0 1 0 1 1 0 0 1 1 1 1 0 0 1 0 1 0 0 1]
[0 0 1 0 1 1 0 0 1 1 1 1 0 0 1 0 1 0 0 1]


In [7]:
# Metrics Calculation
accuracy = np.mean(y_test_predicted == y_test)

In [8]:
# Print the accuracy
print(f"Accuracy (Test): {accuracy:.2f}")

Accuracy (Test): 1.00


Test The model  :

In [9]:
model.predict([[7, 3.2, 4.7, 1.4]])

array([0], dtype=int64)

In [10]:
model.predict([[5.1, 3.4, 1.5, 0.2]])

array([1], dtype=int64)

In [11]:
model.predict([[5, 2.4, 2.5, 2.2]])

array([0], dtype=int64)